spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ss15?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

server:
  port: 8080